all:
  children:
    dwm:
      hosts:
        10.0.0.241:
      vars:
        ansible_user: alex 
        timezone: Australia/Sydney
        storage_pools:
          - { pool_name: "isos", pool_path: "/isos" }
          - { pool_name: "vms", pool_path: "/vms" }
