- hosts: all
  become: yes
  tasks:
  - include_role:
      name: set_timezone

  - include_role:
      name: setup_dwm_debian

  - name: reboot
    ansible.builtin.reboot:

  - include_role:
      name: os_customisation
